#!usr/bin/env python3
import uuid

# UUID module gives a way to create universally unique identifiers.
# UUIDs are 128-bit string values, Which represents a huge number of
# possibilities to guarantee uniqueness on a universal basis.
# Each ID is 128-bits, which means that there are two to the 128th power
# possible combinations. That number is really, really big. Basically the 
# number of random version four UUIDs, which need to be generated in order to
# have just a 50% probability of at least one collision is 2.71 quintillion IDs
# That's basically equivalent to generating one billion IDs per second for
# 85 years before you had a coin toss chance of getting a collision.
# this isn't something that you would use in place of an ID field that is
# autogenerated for you by a database. The main utility of these identifiers
# is that when you want to attach an ID to a piece of information that might
# be used outside your app and exchange with third parties.

# use the uuid4 function is pseudo-random that to uses the underlying
# os.urandom() function to create a random sequence
result = uuid.uuid4()
print("UUID4: ")
print(result)
print(result.hex)  # the hex version doesn't have dashes on it
print(result.urn)  # uniform resource name value: it adds labeling in front
print("~~~~~~~~~~~~~~~~~~~~~~~\n")


# create a UUID using uuid5, which takes a namespace and
# name value. Note that this version is not crypto-safe.
# this is a constant value.
result = uuid.uuid5(uuid.NAMESPACE_DNS, "example.com")
print("UUID5: ")
print(result)
print(result.hex)  # the hex version doesn't have dashes on it
print(result.urn)  # uniform resource name value: it adds labeling in front
print("~~~~~~~~~~~~~~~~~~~~~~~\n")

# CONSOLE OUTPUT (will vary the UUID4 results!):
# UUID4:
# 841d065f-c2c4-479e-ac2b-614154963c0b
# 841d065fc2c4479eac2b614154963c0b
# urn:uuid:841d065f-c2c4-479e-ac2b-614154963c0b
# ~~~~~~~~~~~~~~~~~~~~~~~
#
# UUID5:
# cfbff0d1-9375-5685-968c-48ce8b15ae17
# cfbff0d193755685968c48ce8b15ae17
# urn:uuid:cfbff0d1-9375-5685-968c-48ce8b15ae17
# ~~~~~~~~~~~~~~~~~~~~~~~
